package com.bankingcore.bankingledger.domain.entity;

import com.bankingcore.bankingledger.domain.enums.AccountStatus;
import com.bankingcore.bankingledger.domain.enums.AccountType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.SQLRestriction;

import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 * Account entity — represents a bank account in the ledger.
 *
 * Balance rules (enforced at service layer, not DB):
 *  - balance is always the running total of all settled ledger entries
 *  - balance is never modified directly — the double-entry ledger updates it
 *  - scale is always 2 decimal places, rounding HALF_EVEN (banker's rounding)
 *
 * Table: accounts
 */
@Entity
@Table(
        name = "accounts",
        indexes = {
                @Index(name = "idx_accounts_owner",  columnList = "owner_id"),
                @Index(name = "idx_accounts_number", columnList = "account_number")
        }
)
@SQLRestriction("deleted = false")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Account extends BaseEntity {

    // ── Owner ─────────────────────────────────────────────────────────────────

    /**
     * Many accounts → one user.
     * LAZY loading: we don't need the full User graph just to read a balance.
     * FetchType.LAZY is always the correct default for @ManyToOne in a ledger.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "owner_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_accounts_owner"))
    private User owner;

    // ── Identification ────────────────────────────────────────────────────────

    /**
     * Human-readable account number (e.g. "ACC-000001").
     * Generated by AccountService, not the DB — keeps format business-controlled.
     */
    @Column(name = "account_number", nullable = false, unique = true, length = 30)
    private String accountNumber;

    @Enumerated(EnumType.STRING)
    @Column(name = "account_type", nullable = false, length = 20)
    private AccountType accountType;

    // ── Financial ─────────────────────────────────────────────────────────────

    /**
     * ISO 4217 currency code (e.g. "USD", "EUR", "INR").
     * Stored as a String; validated against a currency whitelist in the service.
     */
    @Column(name = "currency", nullable = false, length = 3)
    private String currency;

    /**
     * Current settled balance.
     * precision=19, scale=2 → supports up to 17 digits before decimal point.
     * Sufficient for even the largest institutional accounts.
     * NEVER use double or float for monetary values.
     */
    @Column(name = "balance", nullable = false,
            precision = 19, scale = 2)
    @Builder.Default
    private BigDecimal balance = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_EVEN);

    /**
     * Minimum allowed balance (may be negative for overdraft accounts).
     */
    @Column(name = "minimum_balance", nullable = false,
            precision = 19, scale = 2)
    @Builder.Default
    private BigDecimal minimumBalance = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_EVEN);

    // ── Status ────────────────────────────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 25)
    @Builder.Default
    private AccountStatus status = AccountStatus.PENDING_VERIFICATION;

    // ── Business helpers ──────────────────────────────────────────────────────

    /**
     * Returns true if the account can send or receive transactions.
     * Services should call this before processing any debit or credit.
     */
    public boolean isOperational() {
        return status == AccountStatus.ACTIVE;
    }

    /**
     * Checks whether debiting {@code amount} would breach the minimum balance.
     */
    public boolean hasSufficientFunds(BigDecimal amount) {
        return balance.subtract(amount)
                .compareTo(minimumBalance) >= 0;
    }

    /**
     * Credits the account (adds to balance).
     * Called exclusively by the ledger service — do not call directly from controllers.
     */
    public void credit(BigDecimal amount) {
        this.balance = this.balance
                .add(amount)
                .setScale(2, RoundingMode.HALF_EVEN);
    }

    /**
     * Debits the account (subtracts from balance).
     * Called exclusively by the ledger service — do not call directly from controllers.
     */
    public void debit(BigDecimal amount) {
        this.balance = this.balance
                .subtract(amount)
                .setScale(2, RoundingMode.HALF_EVEN);
    }
}